### ISSUE TITLE
Oh my god...

### ISSUE THREAD

**Issue by IMYdev** [lvkv/whenfs#1]
What a time to be alive... Rust, filesystems and a calendar app written in Java
![image](https://github.com/user-attachments/assets/fc9db894-9749-4340-a9fc-22929b72445f)

**Comment by lvkv** [comment]
Indeed!

**Comment by jamesfulford** [comment]
You absolute madlad.

**Comment by sounddrill31** [comment]
> What a time to be alive... Rust, filesystems and a calendar app written in Java ![image](https://private-user-images.githubusercontent.com/121319594/355529216-fc9db894-9749-4340-a9fc-22929b72445f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Nzk4MDMsIm5iZiI6MTczNDk3OTUwMywicGF0aCI6Ii8xMjEzMTk1OTQvMzU1NTI5MjE2LWZjOWRiODk0LTk3NDktNDM0MC1hOWZjLTIyOTI5YjcyNDQ1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxODQ1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTY1M2NhYTI4ZTFkZjRlOTFkNWI0MjMzNWZiYTE4MTA2NmJmMGYzN2RlNTk3YzFlODdkMDUxNGJiYmE3ZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X3eLeCFvPdNDTHHIbN9AcUbgfzK1mC23uNLHmYYZrmU)

That FS When 😄
